"""Poker44 bot detector — dispersion-based typicality model (pure stdlib).

DESIGN (validated on the public benchmark releases 2026-07-15 / 2026-07-16)
---------------------------------------------------------------------------
Real bot chunks on this subnet are NOT shifted from humans on any single
behavioral statistic — the bot population is heterogeneous (many bot families,
tight-passive through loose-aggressive), so bot/human MEANS nearly coincide
while bot DISPERSION is systematically larger. Humans cluster centrally on
every censored feature; each bot family is an outlier in its own direction.

The detector therefore scores TYPICALITY, not direction:

    1. extract chunk-level behavioral features (per-street fold/raise rates,
       street-reach fractions, bet-sizing spread/entropy, cross-hand
       fold-ratio dispersion) from the censored hands;
    2. measure |feature - human_center| / scale  (two-sided robust z);
    3. combine with logistic-regression weights trained on labeled
       benchmark chunks (fit on one release, verified on the other);
    4. pass through a monotone piecewise calibration so the decision
       threshold sits at 0.5 (bots >= 0.5, humans < 0.5), which the
       validator's threshold_sanity gate requires. The mapping is strictly
       monotone, so ranking metrics (AP, recall@FPR) are unaffected.

Everything here is pure Python stdlib — no numpy/sklearn needed at inference,
so the module imports in any miner environment and scores a chunk in ~100us.

Trained parameters live in neurons/detector_params.py (auto-generated by
local_test/train_detector.py; regenerate by rerunning that script).
"""

from __future__ import annotations

import math
from collections import Counter
from typing import Any, Dict, List

try:  # auto-generated by local_test/train_detector.py
    from neurons.detector_params import PARAMS
except Exception:  # pragma: no cover - params not generated yet
    PARAMS = None

# Score returned when a chunk is empty/degenerate. Kept below 0.5 so a
# malformed human chunk is never flagged as a bot by default.
_NEUTRAL_SCORE = 0.45


def _shannon(counter: Counter) -> float:
    """Natural-log Shannon entropy of a Counter's value distribution."""
    total = sum(counter.values())
    if total <= 0:
        return 0.0
    return -sum((c / total) * math.log(c / total) for c in counter.values() if c > 0)


def _std(values: List[float]) -> float:
    """Population standard deviation (ddof=0), matching training."""
    n = len(values)
    if n <= 1:
        return 0.0
    mean = sum(values) / n
    return math.sqrt(sum((v - mean) ** 2 for v in values) / n)


def extract_features(chunk: List[Dict[str, Any]]) -> Dict[str, float]:
    """Chunk-level behavioral features from CENSORED hands.

    Must stay bit-identical to the extractor used by
    local_test/train_detector.py (which imports this function), so the
    deployed model always sees the exact feature definitions it was
    trained on.
    """
    n_hands = len(chunk)
    street_tot: Counter = Counter()
    street_fold: Counter = Counter()
    street_raise: Counter = Counter()
    bets: List[float] = []
    fold_fracs: List[float] = []
    reach: Counter = Counter()

    for hand in chunk:
        actions = hand.get("actions") or []
        streets = {
            str(s.get("street", "")).lower() for s in (hand.get("streets") or [])
        }
        for street in ("flop", "turn", "river"):
            if street in streets:
                reach[street] += 1

        n_actions = len(actions)
        folds = 0
        for action in actions:
            action_type = action.get("action_type")
            street = str(action.get("street", "")).lower()
            street_tot[street] += 1
            if action_type == "fold":
                street_fold[street] += 1
                folds += 1
            elif action_type == "raise":
                street_raise[street] += 1
            if action_type in ("bet", "raise"):
                bets.append(round(float(action.get("normalized_amount_bb") or 0.0), 2))
        if n_actions > 0:
            fold_fracs.append(folds / n_actions)

    bet_counter = Counter(bets)
    n_bets = len(bets)
    return {
        "flop_fold_rate": street_fold["flop"] / max(1, street_tot["flop"]),
        "turn_fold_rate": street_fold["turn"] / max(1, street_tot["turn"]),
        "river_fold_rate": street_fold["river"] / max(1, street_tot["river"]),
        "flop_raise_rate": street_raise["flop"] / max(1, street_tot["flop"]),
        "xhand_fold_ratio_std": _std(fold_fracs),
        "betsize_std_bb": _std(bets),
        # Entropy/unique-count normalized by bet volume so the features do not
        # track chunk size (30- vs 40-hand chunks) instead of behavior.
        "betsize_entropy_norm": _shannon(bet_counter) / math.log(max(2, n_bets)),
        "betsize_frac_unique": len(bet_counter) / max(1, n_bets),
        "frac_hands_reach_flop": reach["flop"] / max(1, n_hands),
        "frac_hands_reach_river": reach["river"] / max(1, n_hands),
    }


def _calibrate(p: float, threshold: float) -> float:
    """Monotone piecewise-linear map sending `threshold` to 0.5.

    Preserves score ordering exactly (AP / recall@FPR unchanged) while
    centering the operational decision point on 0.5 for the validator's
    threshold_sanity gate.
    """
    t = min(max(threshold, 1e-6), 1.0 - 1e-6)
    if p <= t:
        return 0.5 * (p / t)
    return 0.5 + 0.5 * (p - t) / (1.0 - t)


def score_chunk(chunk: List[Dict[str, Any]]) -> float:
    """One bot-risk score in [0, 1] for a chunk of censored hands."""
    if not chunk or PARAMS is None:
        return _NEUTRAL_SCORE

    features = extract_features(chunk)
    logit = PARAMS["bias"]
    for name, center, scale, weight in PARAMS["features"]:
        z = abs(features[name] - center) / scale
        logit += weight * z
    probability = 1.0 / (1.0 + math.exp(-max(-30.0, min(30.0, logit))))
    calibrated = _calibrate(probability, PARAMS["threshold"])
    return round(min(0.999, max(0.001, calibrated)), 6)
