"""Auto-generated by local_test/train_detector.py — do not edit by hand.

Trained on banked Poker44 benchmark releases: 2026-07-15, 2026-07-16
(284 labeled chunk groups). Regenerate by rerunning the script.
"""

PARAMS = {
    "features": [
        ("flop_fold_rate", 0.25, 0.0976157065868327, 0.36866588662114436),
        ("turn_fold_rate", 0.25, 0.14688947336467648, 0.43872059590224644),
        ("river_fold_rate", 0.1715686274509804, 0.12915889565775635, 0.7203225051114248),
        ("flop_raise_rate", 0.02532051282051282, 0.043371395878790193, 0.7479541703941885),
        ("xhand_fold_ratio_std", 0.2707468012544065, 0.03953261088609557, 0.5054001439770743),
        ("betsize_std_bb", 38.39031924347691, 5.938751851711135, 0.2521570777649057),
        ("betsize_entropy_norm", 0.9514651569223582, 0.03842347962218245, 0.04467994517640204),
        ("betsize_frac_unique", 0.8927544565842438, 0.064743970414969, 0.4118158879306194),
        ("frac_hands_reach_flop", 0.45, 0.12744496531691826, 0.6957177472890242),
        ("frac_hands_reach_river", 0.16666666666666666, 0.08245917057475137, 0.43990622717663086),
    ],
    "bias": -3.456314588665659,
    "threshold": 0.6594115233090945,
}
