"""Poker44 bot detector — dispersion-based typicality model (pure stdlib).

DESIGN (validated on the public benchmark releases 2026-07-15 / 2026-07-16)
---------------------------------------------------------------------------
Real bot chunks on this subnet are NOT shifted from humans on any single
behavioral statistic — the bot population is heterogeneous (many bot families,
tight-passive through loose-aggressive), so bot/human MEANS nearly coincide
while bot DISPERSION is systematically larger. Humans cluster centrally on
every censored feature; each bot family is an outlier in its own direction.

The detector therefore scores TYPICALITY, not direction:

    1. extract chunk-level behavioral features (per-street fold/raise rates,
       street-reach fractions, bet-sizing spread/entropy, cross-hand
       fold-ratio dispersion) from the censored hands;
    2. measure |feature - human_center| / scale  (two-sided robust z);
    3. combine with logistic-regression weights trained on labeled
       benchmark chunks (fit on one release, verified on the other);
    4. pass through a monotone piecewise calibration so the decision
       threshold sits at 0.5 (bots >= 0.5, humans < 0.5), which the
       validator's threshold_sanity gate requires. The mapping is strictly
       monotone, so ranking metrics (AP, recall@FPR) are unaffected.

Everything here is pure Python stdlib — no numpy/sklearn needed at inference,
so the module imports in any miner environment and scores a chunk in ~100us.

Trained parameters live in neurons/detector_params.py (auto-generated by
local_test/train_detector.py; regenerate by rerunning that script).
"""

from __future__ import annotations

import math
import struct
from collections import Counter
from typing import Any, Dict, List

try:  # auto-generated by local_test/train_detector.py
    from neurons.detector_params import PARAMS
except Exception:  # pragma: no cover - params not generated yet
    PARAMS = None

# Score returned when a chunk is empty/degenerate. Kept below 0.5 so a
# malformed human chunk is never flagged as a bot by default.
_NEUTRAL_SCORE = 0.45


def _shannon(counter: Counter) -> float:
    """Natural-log Shannon entropy of a Counter's value distribution."""
    total = sum(counter.values())
    if total <= 0:
        return 0.0
    return -sum((c / total) * math.log(c / total) for c in counter.values() if c > 0)


def _std(values: List[float]) -> float:
    """Population standard deviation (ddof=0), matching training."""
    n = len(values)
    if n <= 1:
        return 0.0
    mean = sum(values) / n
    return math.sqrt(sum((v - mean) ** 2 for v in values) / n)


def _quantile(sorted_vals: List[float], q: float) -> float:
    """Quantile with linear interpolation (numpy default) on pre-sorted values."""
    n = len(sorted_vals)
    if n == 1:
        return sorted_vals[0]
    pos = q * (n - 1)
    lo = int(math.floor(pos))
    hi = min(lo + 1, n - 1)
    frac = pos - lo
    return sorted_vals[lo] + frac * (sorted_vals[hi] - sorted_vals[lo])


# Aggregation suffixes applied to every per-hand statistic, in fixed order.
_AGG_SUFFIXES = ("mean", "std", "min", "max", "q10", "q50", "q90")


def _aggregate(name: str, values: List[float], out: Dict[str, float]) -> None:
    """Write the 7 chunk-level aggregates of a per-hand stat into `out`."""
    if not values:
        for suffix in _AGG_SUFFIXES:
            out[f"{name}__{suffix}"] = 0.0
        return
    s = sorted(values)
    n = len(s)
    out[f"{name}__mean"] = float(sum(s) / n)
    out[f"{name}__std"] = float(_std(values))
    out[f"{name}__min"] = float(s[0])
    out[f"{name}__max"] = float(s[-1])
    out[f"{name}__q10"] = float(_quantile(s, 0.10))
    out[f"{name}__q50"] = float(_quantile(s, 0.50))
    out[f"{name}__q90"] = float(_quantile(s, 0.90))


def _norm_entropy(values: List[Any]) -> float:
    """Normalized Shannon entropy (natural log) over value counts.

    Divided by log(max(2, distinct_count)); 0.0 when <= 1 distinct value.
    """
    counter = Counter(values)
    distinct = len(counter)
    if distinct <= 1:
        return 0.0
    return _shannon(counter) / math.log(max(2, distinct))


def _max_run(values: List[Any]) -> int:
    """Length of the longest run of identical consecutive values."""
    best = 0
    run = 0
    prev = object()
    for v in values:
        run = run + 1 if v == prev else 1
        prev = v
        best = max(best, run)
    return best


def _parity_hands(chunk: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Chunk-size parity between live (80-100 hands) and benchmark (30-40).

    Size-dependent aggregates (std, quantiles) shift with hand count, so
    chunks longer than 40 hands are deterministically subsampled to 35 hands
    evenly spaced by index, always including the last hand (no randomness).
    Hands with fewer than 5 actions are then dropped: live hands always carry
    5-8 actions post-censor, while benchmark stragglers below 5 actions
    create fake dispersion the live side never sees.
    """
    hands = chunk
    n = len(hands)
    if n > 40:
        k = 35
        hands = [hands[(i * (n - 1)) // (k - 1)] for i in range(k)]
    return [h for h in hands if len(h.get("actions") or []) >= 5]


# Per-hand statistics, in the fixed order used to build CANDIDATE_FEATURES.
_PER_HAND_STATS = (
    "fold_share",
    "call_share",
    "check_share",
    "bet_share",
    "raise_share",
    "aggression_share",
    "passive_share",
    "preflop_share",
    "postflop_share",
    "action_entropy",
    "actor_entropy",
    "street_entropy",
    "actor_switch_rate",
    "actor_run_max_share",
    "action_run_max_share",
    "unique_actor_share",
    "player_count",
    "seat_utilization",
    "street_count",
    "hero_action_share",
    "raise_to_present_share",
    "call_to_present_share",
    "nonzero_amount_share",
)

_CHUNK_LEVEL_FEATURES = (
    "thr_aggr_ge35",
    "thr_action_entropy_le35",
    "thr_actor_entropy_ge75",
    "sig_action_top_share",
    "sig_action_unique_share",
    "sig_actor_top_share",
    "sig_actor_unique_share",
    "sig_street_top_share",
    "sig_street_unique_share",
)

# ---- action n-gram token vocabulary (fixed, deterministic order) ----------
# Short "phrases" of play, normalized per hand so 30-hand benchmark chunks
# and 80-100-hand live chunks stay comparable. Only censor-surviving action
# types appear. Pot-ratio buckets use amount/pot_before — a ratio of two
# same-scale quantities, so it does not inherit the absolute-bb scale shift
# that killed the raw bet-size features (the transfer gate still vets every
# token individually).
_ACTION_CODE = {"fold": "f", "call": "c", "check": "k", "bet": "b", "raise": "r"}
_STREET_CODE = {"preflop": "p", "flop": "f", "turn": "t", "river": "r"}
_NG1_TOKENS = tuple(
    f"ng1_{s}{a}" for s in "pftr" for a in "fckbr"
)  # 20 street+action unigrams
_NG2_TOKENS = tuple(
    f"ng2_{a}{b}" for a in "fckbr" for b in "fckbr"
)  # 25 action bigrams
_POT_BUCKETS = ("z", "s", "m", "p", "o")  # 0 / <0.4 / <0.9 / <1.5 / >=1.5
_NGP_TOKENS = tuple(
    f"ngp_{a}{b}" for a in "br" for b in _POT_BUCKETS
)  # 10 sized-aggression tokens
_NGRAM_FEATURES = _NG1_TOKENS + _NG2_TOKENS + _NGP_TOKENS


def _pot_bucket(amount: float, pot_before: float) -> str:
    if amount <= 0 or pot_before <= 0:
        return "z"
    ratio = amount / pot_before
    if ratio < 0.4:
        return "s"
    if ratio < 0.9:
        return "m"
    if ratio < 1.5:
        return "p"
    return "o"

# Candidate feature names for the trainer's transfer gate: every new
# aggregate/chunk-level feature plus the scale-free legacy features. The
# three betsize_* legacy features are EXCLUDED (verified 340x
# out-of-distribution live vs benchmark).
CANDIDATE_FEATURES: List[str] = (
    [f"{stat}__{agg}" for stat in _PER_HAND_STATS for agg in _AGG_SUFFIXES]
    + list(_CHUNK_LEVEL_FEATURES)
    + list(_NGRAM_FEATURES)
    + [
        "flop_fold_rate",
        "turn_fold_rate",
        "river_fold_rate",
        "flop_raise_rate",
        "frac_hands_reach_flop",
        "frac_hands_reach_river",
        "xhand_fold_ratio_std",
    ]
)


def extract_features(chunk: List[Dict[str, Any]]) -> Dict[str, float]:
    """Chunk-level behavioral features from CENSORED hands.

    Must stay bit-identical to the extractor used by
    local_test/train_detector.py (which imports this function), so the
    deployed model always sees the exact feature definitions it was
    trained on.

    Chunk-size parity is applied first (see _parity_hands); every feature
    is computed on the resulting hand list.
    """
    hands = _parity_hands(chunk)
    n_hands = len(hands)
    street_tot: Counter = Counter()
    street_fold: Counter = Counter()
    street_raise: Counter = Counter()
    bets: List[float] = []
    fold_fracs: List[float] = []
    reach: Counter = Counter()

    per_hand: Dict[str, List[float]] = {stat: [] for stat in _PER_HAND_STATS}
    sig_action: Counter = Counter()
    sig_actor: Counter = Counter()
    sig_street: Counter = Counter()
    ngram_counts: Counter = Counter()

    for hand in hands:
        actions = hand.get("actions") or []
        streets = {
            str(s.get("street", "")).lower() for s in (hand.get("streets") or [])
        }
        for street in ("flop", "turn", "river"):
            if street in streets:
                reach[street] += 1

        n_actions = len(actions)
        folds = 0
        for action in actions:
            action_type = action.get("action_type")
            street = str(action.get("street", "")).lower()
            street_tot[street] += 1
            if action_type == "fold":
                street_fold[street] += 1
                folds += 1
            elif action_type == "raise":
                street_raise[street] += 1
            if action_type in ("bet", "raise"):
                bets.append(round(float(action.get("normalized_amount_bb") or 0.0), 2))
        if n_actions > 0:
            fold_fracs.append(folds / n_actions)

        # ---- per-hand statistics -----------------------------------------
        action_types = [a.get("action_type") for a in actions]
        actor_seats = [a.get("actor_seat") for a in actions]
        action_streets = [str(a.get("street", "")).lower() for a in actions]
        type_counts = Counter(action_types)

        meaningful = max(
            1,
            sum(type_counts[t] for t in ("call", "check", "bet", "raise", "fold")),
        )
        n_all = max(1, n_actions)
        players = hand.get("players") or []
        metadata = hand.get("metadata") or {}
        player_count = len(players)
        hero_seat = metadata.get("hero_seat")

        per_hand["fold_share"].append(type_counts["fold"] / meaningful)
        per_hand["call_share"].append(type_counts["call"] / meaningful)
        per_hand["check_share"].append(type_counts["check"] / meaningful)
        per_hand["bet_share"].append(type_counts["bet"] / meaningful)
        per_hand["raise_share"].append(type_counts["raise"] / meaningful)
        per_hand["aggression_share"].append(
            (type_counts["bet"] + type_counts["raise"]) / meaningful
        )
        per_hand["passive_share"].append(
            (type_counts["call"] + type_counts["check"]) / meaningful
        )
        n_preflop = sum(1 for s in action_streets if s == "preflop")
        per_hand["preflop_share"].append(n_preflop / n_all)
        per_hand["postflop_share"].append((n_actions - n_preflop) / n_all)
        per_hand["action_entropy"].append(_norm_entropy(action_types))
        per_hand["actor_entropy"].append(_norm_entropy(actor_seats))
        per_hand["street_entropy"].append(_norm_entropy(action_streets))
        per_hand["actor_switch_rate"].append(
            sum(1 for j in range(1, n_actions) if actor_seats[j] != actor_seats[j - 1])
            / max(1, n_actions - 1)
        )
        per_hand["actor_run_max_share"].append(_max_run(actor_seats) / n_all)
        per_hand["action_run_max_share"].append(_max_run(action_types) / n_all)
        per_hand["unique_actor_share"].append(
            len(set(actor_seats)) / max(1, player_count)
        )
        per_hand["player_count"].append(float(player_count))
        per_hand["seat_utilization"].append(
            player_count / max(1, metadata.get("max_seats") or 0)
        )
        per_hand["street_count"].append(float(len(hand.get("streets") or [])))
        per_hand["hero_action_share"].append(
            sum(1 for s in actor_seats if s == hero_seat) / n_all
        )
        per_hand["raise_to_present_share"].append(
            sum(1 for a in actions if a.get("raise_to") is not None) / n_all
        )
        per_hand["call_to_present_share"].append(
            sum(1 for a in actions if a.get("call_to") is not None) / n_all
        )
        per_hand["nonzero_amount_share"].append(
            sum(1 for a in actions if (a.get("amount") or 0) > 0) / n_all
        )

        sig_action[tuple(action_types)] += 1
        sig_actor[tuple(actor_seats)] += 1
        sig_street[tuple(action_streets)] += 1

        # ---- n-gram tokens (counts accumulated chunk-wide) ---------------
        codes: List[str] = []
        for a in actions:
            code = _ACTION_CODE.get(str(a.get("action_type", "")))
            if code is None:
                codes.append("")
                continue
            codes.append(code)
            street_c = _STREET_CODE.get(str(a.get("street", "")).lower())
            if street_c is not None:
                ngram_counts[f"ng1_{street_c}{code}"] += 1
            if code in ("b", "r"):
                bucket = _pot_bucket(
                    float(a.get("amount") or 0.0),
                    float(a.get("pot_before") or 0.0),
                )
                ngram_counts[f"ngp_{code}{bucket}"] += 1
        for j in range(1, len(codes)):
            if codes[j - 1] and codes[j]:
                ngram_counts[f"ng2_{codes[j - 1]}{codes[j]}"] += 1

    bet_counter = Counter(bets)
    n_bets = len(bets)
    features: Dict[str, float] = {
        "flop_fold_rate": street_fold["flop"] / max(1, street_tot["flop"]),
        "turn_fold_rate": street_fold["turn"] / max(1, street_tot["turn"]),
        "river_fold_rate": street_fold["river"] / max(1, street_tot["river"]),
        "flop_raise_rate": street_raise["flop"] / max(1, street_tot["flop"]),
        "xhand_fold_ratio_std": _std(fold_fracs),
        "betsize_std_bb": _std(bets),
        # Entropy/unique-count normalized by bet volume so the features do not
        # track chunk size (30- vs 40-hand chunks) instead of behavior.
        "betsize_entropy_norm": _shannon(bet_counter) / math.log(max(2, n_bets)),
        "betsize_frac_unique": len(bet_counter) / max(1, n_bets),
        "frac_hands_reach_flop": reach["flop"] / max(1, n_hands),
        "frac_hands_reach_river": reach["river"] / max(1, n_hands),
    }

    for stat in _PER_HAND_STATS:
        _aggregate(stat, per_hand[stat], features)

    # ---- chunk-level features -------------------------------------------
    n_h = max(1, n_hands)
    features["thr_aggr_ge35"] = (
        sum(1 for v in per_hand["aggression_share"] if v >= 0.35) / n_h
    )
    features["thr_action_entropy_le35"] = (
        sum(1 for v in per_hand["action_entropy"] if v <= 0.35) / n_h
    )
    features["thr_actor_entropy_ge75"] = (
        sum(1 for v in per_hand["actor_entropy"] if v >= 0.75) / n_h
    )
    for prefix, counter in (
        ("sig_action", sig_action),
        ("sig_actor", sig_actor),
        ("sig_street", sig_street),
    ):
        top = counter.most_common(1)[0][1] if counter else 0
        features[f"{prefix}_top_share"] = top / n_h
        features[f"{prefix}_unique_share"] = len(counter) / n_h

    # ---- n-gram tokens, normalized per hand ------------------------------
    for token in _NGRAM_FEATURES:
        features[token] = ngram_counts[token] / n_h

    return features


def _calibrate(p: float, threshold: float) -> float:
    """Monotone piecewise-linear map sending `threshold` to 0.5.

    Preserves score ordering exactly (AP / recall@FPR unchanged) while
    centering the operational decision point on 0.5 for the validator's
    threshold_sanity gate.
    """
    t = min(max(threshold, 1e-6), 1.0 - 1e-6)
    if p <= t:
        return 0.5 * (p / t)
    return 0.5 + 0.5 * (p - t) / (1.0 - t)


def _f32(value: float) -> float:
    """Round-trip through IEEE float32 — sklearn casts inputs to float32
    before threshold comparison, and parity requires emulating that."""
    return struct.unpack("f", struct.pack("f", value))[0]


def _eval_tree(tree: Dict[str, List[float]], x: List[float]) -> float:
    """Walk one exported decision tree to its leaf value.

    Flat-array encoding (sklearn layout): f[i] = split feature index
    (-2 for a leaf), t[i] = threshold, l[i]/r[i] = child node indices,
    v[i] = leaf value. Comparison is float32(x) <= float64(threshold),
    exactly as sklearn evaluates it.
    """
    f, t, l, r, v = tree["f"], tree["t"], tree["l"], tree["r"], tree["v"]
    i = 0
    while f[i] >= 0:
        i = l[i] if _f32(x[f[i]]) <= t[i] else r[i]
    return v[i]


def percentile_ranks(values: List[float]) -> List[float]:
    """Tie-averaged percentile ranks in [0, 1].

    The reference implementation for the request-relative rank branch: the
    trainer imports THIS function for the training-time transform, so train
    and serve are identical by construction. n == 1 -> [0.5]; ties share the
    mean of their positional ranks; result divided by (n - 1).
    """
    n = len(values)
    if n == 0:
        return []
    if n == 1:
        return [0.5]
    order = sorted(range(n), key=lambda i: (values[i], i))
    ranks = [0.0] * n
    i = 0
    while i < n:
        j = i
        while j + 1 < n and values[order[j + 1]] == values[order[i]]:
            j += 1
        avg = (i + j) / 2.0
        for k in range(i, j + 1):
            ranks[order[k]] = avg / (n - 1)
        i = j + 1
    return ranks


def _sigmoid(logit: float) -> float:
    return 1.0 / (1.0 + math.exp(-max(-30.0, min(30.0, logit))))


def _member_probability(member: Dict[str, Any], x: List[float]) -> float:
    """Probability of class 1 from one exported ensemble member."""
    kind = member.get("kind")
    if kind == "gbdt":
        # Staged additive regression trees -> logit -> sigmoid.
        logit = member["init"]
        rate = member["learning_rate"]
        for tree in member["trees"]:
            logit += rate * _eval_tree(tree, x)
        return _sigmoid(logit)
    # kind == "forest": averaging classifier — each leaf already stores the
    # class-1 probability of that leaf; the forest averages over trees.
    total = 0.0
    for tree in member["trees"]:
        total += _eval_tree(tree, x)
    return total / max(1, len(member["trees"]))


def _members_probability(members: List[Dict[str, Any]], x: List[float]) -> float:
    """Weighted probability from a list of exported ensemble members."""
    return sum(m["weight"] * _member_probability(m, x) for m in members)


def _manifold_probability(man: Dict[str, Any], x: List[float]) -> float:
    """Human-manifold branch: bot-risk from distance to the human center.

    One-class model fitted on REAL human chunks only (Ledoit-Wolf shrinkage
    covariance); synthetic bots never shape it — they only calibrated the
    d0/s distance-to-probability mapping. Score = sigmoid of the Mahalanobis
    distance from the human center: far from "humanly normal" -> bot-like.
    Real bots, whatever they look like, are not human — so this branch does
    not depend on the benchmark's synthetic bots resembling them.
    """
    return _sigmoid((_manifold_distance(man, x) - man["d0"]) / man["s"])


def _manifold_distance(man: Dict[str, Any], x: List[float]) -> float:
    """Mahalanobis distance from the human center (pure python)."""
    mu = man["mu"]
    prec = man["prec"]
    n = len(mu)
    d = [x[i] - mu[i] for i in range(n)]
    q = 0.0
    for i in range(n):
        di = d[i]
        if di == 0.0:
            continue
        row = prec[i]
        acc = 0.0
        for j in range(n):
            acc += row[j] * d[j]
        q += di * acc
    return math.sqrt(max(0.0, q))


def score_chunks_batch(chunks: List[List[Dict[str, Any]]]) -> List[float]:
    """Score a whole validator request at once (the production path).

    With a rank_blend model this blends two branches per chunk:
      raw branch  — the usual model on absolute feature values;
      rank branch — the same architecture on each feature's tie-averaged
                    percentile rank WITHIN THIS REQUEST, which is immune to
                    benchmark->live scale drift by construction (a chunk at
                    the 80th percentile of its batch is at the 80th
                    percentile in any data distribution).
    Falls back to per-chunk raw scoring for small batches (< 8 chunks, where
    within-request ranks are meaningless) or non-rank_blend params. A chunk
    whose feature extraction fails gets _NEUTRAL_SCORE and is excluded from
    the rank transform; the reply length always equals len(chunks).
    """
    if not chunks or PARAMS is None:
        return [_NEUTRAL_SCORE] * len(chunks)
    if PARAMS.get("model") != "rank_blend" or len(chunks) < 8:
        return [score_chunk(c) for c in chunks]

    names = PARAMS["feature_names"]
    # The RANK branch may use a WIDER feature set than the raw/manifold
    # branches: ranking is scale/location invariant, so mean-shifted features
    # that the strict transfer gate drops for the absolute-scale raw branch
    # still order chunks correctly and add live signal. Defaults to `names`
    # for backward compatibility with pre-v7 params.
    rank_names = PARAMS.get("rank_feature_names", names)
    rows: List[Any] = []          # raw + manifold features (strict set)
    rank_rows: List[Any] = []     # rank-branch features (wide set)
    for chunk in chunks:
        try:
            feats = extract_features(chunk)
            rows.append([feats[n] for n in names])
            rank_rows.append([feats[n] for n in rank_names])
        except Exception:
            rows.append(None)
            rank_rows.append(None)
    valid = [i for i, r in enumerate(rows) if r is not None]

    raw_p: Dict[int, float] = {
        i: _members_probability(PARAMS["raw_members"], rows[i]) for i in valid
    }
    rank_p: Dict[int, float] = {}
    if len(valid) >= 8:
        cols = list(zip(*[rank_rows[i] for i in valid]))
        ranked = [percentile_ranks(list(col)) for col in cols]
        for pos, i in enumerate(valid):
            x_rank = [ranked[j][pos] for j in range(len(rank_names))]
            rank_p[i] = _members_probability(PARAMS["rank_members"], x_rank)
    man = PARAMS.get("manifold")
    man_p: Dict[int, float] = {}
    if man is not None:
        if man.get("output") == "rank" and len(valid) >= 8:
            # Distance-from-human graded on the day's curve: the ABSOLUTE
            # Mahalanobis distance shifts between benchmark and live (joint
            # covariance drift saturated a fixed sigmoid), but the ORDERING
            # of distances within one request survives — so emit each
            # chunk's percentile rank of distance within the request.
            dists = [_manifold_distance(man, rows[i]) for i in valid]
            ranked = percentile_ranks(dists)
            for pos, i in enumerate(valid):
                man_p[i] = ranked[pos]
        else:
            for i in valid:
                man_p[i] = _manifold_probability(man, rows[i])

    # Branch weights: "weights" dict (raw/rank/manifold) with legacy
    # w_raw fallback. Missing branches renormalize among the present ones.
    w = PARAMS.get("weights") or {
        "raw": PARAMS["w_raw"],
        "rank": 1.0 - PARAMS["w_raw"],
        "manifold": 0.0,
    }
    out: List[float] = []
    for i in range(len(chunks)):
        if rows[i] is None:
            out.append(_NEUTRAL_SCORE)
            continue
        parts = [("raw", raw_p[i])]
        if i in rank_p:
            parts.append(("rank", rank_p[i]))
        if i in man_p and w.get("manifold", 0.0) > 0.0:
            parts.append(("manifold", man_p[i]))
        total_w = sum(w.get(k, 0.0) for k, _ in parts)
        if total_w <= 0.0:
            p = raw_p[i]
        else:
            p = sum(w.get(k, 0.0) * v for k, v in parts) / total_w
        out.append(
            round(min(0.999, max(0.001, _calibrate(p, PARAMS["threshold"]))), 6)
        )
    return out


def score_chunk(chunk: List[Dict[str, Any]]) -> float:
    """One bot-risk score in [0, 1] for a chunk of censored hands.

    Single-chunk path: with a rank_blend model this uses the RAW branch only
    (a within-request rank needs the rest of the request — see
    score_chunks_batch, which is what the miner serves with).
    """
    if not chunk or PARAMS is None:
        return _NEUTRAL_SCORE

    features = extract_features(chunk)

    if PARAMS.get("model") == "rank_blend":
        # Single-chunk path: raw branch (+ manifold, which needs no batch);
        # the rank branch requires the rest of the request (batch path).
        x = [features[name] for name in PARAMS["feature_names"]]
        w = PARAMS.get("weights") or {
            "raw": PARAMS["w_raw"],
            "rank": 1.0 - PARAMS["w_raw"],
            "manifold": 0.0,
        }
        parts = [("raw", _members_probability(PARAMS["raw_members"], x))]
        man = PARAMS.get("manifold")
        if man is not None and w.get("manifold", 0.0) > 0.0:
            parts.append(("manifold", _manifold_probability(man, x)))
        total_w = sum(w.get(k, 0.0) for k, _ in parts)
        probability = (
            sum(w.get(k, 0.0) * v for k, v in parts) / total_w
            if total_w > 0
            else parts[0][1]
        )
        calibrated = _calibrate(probability, PARAMS["threshold"])
        return round(min(0.999, max(0.001, calibrated)), 6)

    if PARAMS.get("model") == "ensemble":
        # Weighted blend of heterogeneous tree families (GBDT + ExtraTrees +
        # RandomForest), the structure every top miner on this subnet runs:
        # decorrelated tree families generalize better than a single GBDT on
        # a small, shifting training set. Weights are tuned on out-of-fold
        # predictions against the authoritative validator reward.
        x = [features[name] for name in PARAMS["feature_names"]]
        probability = sum(
            member["weight"] * _member_probability(member, x)
            for member in PARAMS["members"]
        )
    elif PARAMS.get("model") == "gbdt":
        # Single gradient-boosted model (v3 format, kept loadable).
        x = [features[name] for name in PARAMS["feature_names"]]
        logit = PARAMS["init"]
        rate = PARAMS["learning_rate"]
        for tree in PARAMS["trees"]:
            logit += rate * _eval_tree(tree, x)
        probability = _sigmoid(logit)
    else:
        # Legacy linear form: two-sided robust |z| -> logistic weights.
        logit = PARAMS["bias"]
        for name, center, scale, weight in PARAMS["features"]:
            z = abs(features[name] - center) / scale
            logit += weight * z
        probability = _sigmoid(logit)

    calibrated = _calibrate(probability, PARAMS["threshold"])
    return round(min(0.999, max(0.001, calibrated)), 6)
